music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :create, :new, :show]

  resource :session, only: [:create, :destroy, :new]

  root 'sessions#new'
end

music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def self.generate_session_token
     SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def name
    result = ""
    self.email.chars.each do |ltr|
      if ltr == "@"
        break
      end
      result += ltr
    end
    return result
  end

end

music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    return true if session[:session_token]
    false
  end

  def current_user
    return nil unless session[:session_token]
    @current_user = User.find_by(session_token: session[:session_token])
  end
end

music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
    params[:user][:password])

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Incorrect username and/or password']
      render :new
    end
  end

  def destroy
    logout_user(current_user)
    redirect_to new_session_url
  end
end

music/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
  "<input
  type='hidden'
  name='authenticity_token'
  value=#{form_authenticity_token}>".html_safe
  end
end

music/app/helpers/sessions_helper.rb
module SessionsHelper
end

music/app/helpers/users_helper.rb
module UsersHelper
end

music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h1 class="music-app">Music App</h1>
      <%= button_to "Sign Up!", new_user_url, method: "get", class: "nav-btn"%>
      <%= button_to "Sign In!", new_session_url, method: "get", class: "nav-btn"%>
      <% if self.controller.logged_in? %>
      <%= button_to "Logout", session_url, method: "delete", class: 'nav-btn'%>
      <% end %>
    </nav>
    <br>
    <br>

    <%= yield %>
  </body>
</html>

music/app/views/users/index.html.erb
<h1>List of Music App Users!</h1>

<% if logged_in? %>
  <% @users.each do |user| %>
  <h2><%= user.email %></h2>
  <% end %>
<% end %>

music/app/views/users/new.html.erb
<h2>Sign up Here!</h2>
<h3>New user</h3>

<form class="signup" action="<%=users_url%>" method="post">
<input type="hidden" >
<%= auth_token %>

<label for="email">Email</label>
<input id = "email" type="text" name="user[email]">

<label for="password">Password</label>
<input id="password" type="password" name="user[password]">
<input type="submit" value="Submit">
</form>

<br>

music/app/views/users/show.html.erb
<h1>Welcome, <%= @user.name%>!</h1>

<% if logged_in? %>
  <h2><%= @user.email %></h2>
<% end %>